--CREATE DATABASE DEPARTMENT
--USE DEPARTMENT
--CREATE TABLE EMPLOYEE(
--ID int primary key identity,
--FULLNAME nvarchar(50) NOT NULL,
--AGE int Check(AGE>0) NOT NULL,
--EMAIL nvarchar(255) UNIQUE,
--SALARY float NOT NULL CHECK(SALARY>300 AND SALARY<2000)
--)
--INSERT INTO EMPLOYEE VALUES('ELNARA VAHABOVA',19,'7@gmail.com',1854.9)
--INSERT INTO EMPLOYEE VALUES('ELi Veliyev',20,'8@gmail.com',1284.9)
--INSERT INTO EMPLOYEE VALUES('ELNAR VAHABOV',21,'e1@gmail.com',454.9)

--SELECT *FROM EMPLOYEE

--UPDATE EMPLOYEE SET SALARY=1600
--WHERE ID=1

--SELECT *FROM EMPLOYEE
--WHERE SALARY  BETWEEN 500 AND 1500

--SELECT FULLNAME, EMAIL, SALARY FROM EMPLOYEE
--ORDER BY SALARY DESC

--CREATE DATABASE SCHOOL
--USE SCHOOL
 
--CREATE TABLE STUDENTs(
--ID INT PRIMARY KEY IDENTITY,
--NAME NVARCHAR(30) NOT NULL,
--SURNAME NVARCHAR(50),
--PHONE INT UNIQUE,
--SCORE FLOAT DEFAULT(50),
--COMMENT NVARCHAR(255),
--ISGRADUATED BIT DEFAULT(0)
--)
--INSERT INTO STUDENTs VALUES('ELNARA','VAHABOVA',0504444456,97,'E',0)
--INSERT INTO STUDENTs VALUES('ELNAR','VAHABOV',0504444459,92,'V',1)
--INSERT INTO STUDENTs VALUES('ELCIN','VAHABOV',0504444453,68,'B',1)
--INSERT INTO STUDENTs VALUES('rtrtr','VAHABOV',0504444453,68,'B',1)
--UPDATE STUDENTs SET COMMENT='CONGRATULATIONS'
--WHERE SCORE>(SELECT AVG(SCORE) FROM STUDENTs)

--SELECT *FROM STUDENTs

--UPDATE STUDENTs SET COMMENT='SO BAD'
--WHERE SCORE<(SELECT AVG(SCORE) FROM STUDENTs)

--CREATE TABLE GRADUATEDSTUDENTS(
--ID INT PRIMARY KEY IDENTITY,
--NAME NVARCHAR(30) NOT NULL,
--SURNAME NVARCHAR(50),
--PHONE INT UNIQUE,
--SCORE FLOAT DEFAULT(50),
--COMMENT NVARCHAR(255),
--ISGRADUATED BIT DEFAULT(0)
--)

--INSERT INTO GRADUATEDSTUDENTS
--SELECT NAME FROM STUDENT
--WHERE ISGRADUATED=1

--DELETE FROM STUDENT
--WHERE ISGRADUATED=1

CREATE DATABASE DEPARTMENTS
USE DEPARTMENTS

CREATE TABLE ISCI(
MKOD INT,
ID INT PRIMARY KEY IDENTITY,
VezifeID INT,
NAME NVARCHAR(30) NOT NULL,
SURNAME NVARCHAR(50) DEFAULT('XXXX'),
FNAME NVARCHAR(30) NOT NULL,
SALARY INT
)

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR(50)
)

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR(100)
)

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100),
APRICE FLOAT,
SPRICE FLOAT
)

CREATE TABLE SELL(
ID INT PRIMARY KEY IDENTITY,
MehsulID INT REFERENCES MEHSUL(ID),
IsciID INT REFERENCES ISCI(ID),
SALE FLOAT,
DATE DATE
)

INSERT INTO SELL VALUES(3.1,2020-12-23)
 
SELECT COUNT(NAME) FROM ISCI

SELECT * FROM ISCI
ORDER BY SALARY DESC

